<<<<<<< HEAD
# Generated by Django 4.2.9 on 2024-01-27 05:51
=======
# Generated by Django 4.2.9 on 2024-01-27 14:00
>>>>>>> db7da377018814ee68b3cb43a78d2f594d7e580f

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedImage",
<<<<<<< HEAD
=======
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="user_problem_images/")),
            ],
        ),
        migrations.CreateModel(
            name="UserModel",
            fields=[
                (
                    "user",
                    models.TextField(primary_key=True, serialize=False, unique=True),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("pincode", models.CharField(blank=True, max_length=10, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ZenCoins",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="zenapp.usermodel",
                    ),
                ),
                ("zen_coins", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="UserProblem",
>>>>>>> db7da377018814ee68b3cb43a78d2f594d7e580f
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
<<<<<<< HEAD
                ("image", models.ImageField(upload_to="user_problem_images/")),
            ],
        ),
        migrations.CreateModel(
            name="UserModel",
            fields=[
                (
                    "user",
                    models.TextField(primary_key=True, serialize=False, unique=True),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("pincode", models.CharField(blank=True, max_length=10, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ZenCoins",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="zenapp.usermodel",
                    ),
                ),
                ("zen_coins", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="UserProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
=======
>>>>>>> db7da377018814ee68b3cb43a78d2f594d7e580f
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Submitted", "Submitted"),
                            ("In Progress", "In Progress"),
                            ("Solved", "Solved"),
                        ],
                        default="Submitted",
                        max_length=20,
                    ),
                ),
                ("image", models.ImageField(upload_to="user_problem_images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
<<<<<<< HEAD
                        related_name="user_problems",
=======
                        related_name="images",
>>>>>>> db7da377018814ee68b3cb43a78d2f594d7e580f
                        to="zenapp.usermodel",
                    ),
                ),
            ],
        ),
    ]
