# Generated by Django 4.2.9 on 2024-01-26 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zenapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usermodel",
            old_name="user_id",
            new_name="user",
        ),
    ]
