# Generated by Django 4.2.9 on 2024-01-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zenapp", "0002_rename_user_id_usermodel_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="user_problem_images/")),
            ],
        ),
    ]
