// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwHUmbFE1Ngy0dqX0hiEFkfVWlJIWMNwc',
    appId: '1:342146811607:web:d5bcc74ce1056ac86c5292',
    messagingSenderId: '342146811607',
    projectId: 'zenapp-temporary-appli',
    authDomain: 'zenapp-temporary-appli.firebaseapp.com',
    storageBucket: 'zenapp-temporary-appli.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVEe3x3FFODWWDGhQbcv0lsxIMfow6CpQ',
    appId: '1:342146811607:android:8f8dfed2079977a66c5292',
    messagingSenderId: '342146811607',
    projectId: 'zenapp-temporary-appli',
    storageBucket: 'zenapp-temporary-appli.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKSA3dx2XzKzExLwuqVs7MjF87cGyGcBo',
    appId: '1:342146811607:ios:16e6874b4b51c4556c5292',
    messagingSenderId: '342146811607',
    projectId: 'zenapp-temporary-appli',
    storageBucket: 'zenapp-temporary-appli.appspot.com',
    iosBundleId: 'com.example.ecozen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKSA3dx2XzKzExLwuqVs7MjF87cGyGcBo',
    appId: '1:342146811607:ios:547f306bd199b9af6c5292',
    messagingSenderId: '342146811607',
    projectId: 'zenapp-temporary-appli',
    storageBucket: 'zenapp-temporary-appli.appspot.com',
    iosBundleId: 'com.example.ecozen.RunnerTests',
  );
}
